### ISSUE TITLE
Upgrade atlasu - vnitrni prostredi - zelezo

### ISSUE THREAD

**Issue by TomasKulhanek** [creative-connections/Bodylight-Scenarios#26]
- [ ] http://www.physiome.cz/atlas/vnitrniProstredi/04/
- [ ] vyhledat flash zdrojaky
- [ ] prevest fla podkapitol na html/js
- [ ] vysledek vcetne audia do p:/KofrlabData/UpgradeAtlasu/VnitrniProstredi/04

**Comment by KlaraGrafik** [comment]
Zdrojové .fla soubory se neshodují s verzí online atlasu. Pokusit se vyřešit, až půjdou servery K: kofrlab

**Comment by TomasKulhanek** [comment]
OK.
