### ISSUE TITLE
Editor for educational text - scenarios

### ISSUE THREAD

**Issue by hamu-marc** [creative-connections/Bodylight-Scenarios#36]
- [x] sample text and simulator
- [x] editor workflow
- [x] static,default in WIKI of Bodylight-Scenarios
- [ ] dynamic/local changes in local copy of wiki git -can be commited to github repo
- [x] add settings item for url to scenarios documents WIKI/MD with scenarios,, default url for scenarios pointing to github WIKI pages
- [x] render correct baseurl for md/wiki links
- [x] parse target from #/scenario/[targetwikimd]

**Comment by TomasKulhanek** [comment]
showdown - do not have baseurl settings yet (https://github.com/showdownjs/showdown/pull/671). Thus switched to marked https://marked.js.org/#/USING_ADVANCED.md  

TODO need to check image rendering.
