### ISSUE TITLE
Požadavky pro editor scénářů a kapitol

### ISSUE THREAD

**Issue by TomasKulhanek** [creative-connections/Bodylight-Scenarios#37]
Požadavky pro editor scénářů a kapitol https://github.com/creative-connections/Bodylight-Scenarios/wiki
- [x] možnost editace a preview v githubu 
- [x] renderování markdown (MD) syntaxe do applikace virtuálního pacienta
- [x] renderování externích obrázků (absolute URL)
- [x] simulátory jako webcomponents a custom elements v MD
- [x] renderování obrázků - přidaných do WIKI (relative URL) - added baseImgUrl to marked
- [x] navigace mezi kapitolami
- [x] zvážit jiné formáty (creole wiki)
- [x] zvážit jiné zdroje (wikiskripta, moodle)
- [ ] u simulátoru z Bodylight-Composeru mít přepínač, který přepne-vyvolá okno s bodylight composerem
- [x] snadnější přidání obrázku. Nyní se musí pro relativeURL 1. `git clone https://github.com/creative-connections/Bodylight-Scenarios.wiki.git` 2. add image to images folder 3. `git add images/newimage.png` 4. `git commit -m 'image'` 5. `git pull` nebo dát externě a mít absolute URL

**Comment by kofranek** [comment]
zítra budu v práce

J.

út 19. 5. 2020 v 13:10 odesílatel Tomas Kulhanek <notifications@github.com>
napsal:
