### ISSUE TITLE
Vytvořit animaci nahrávání webové aplikace.

### ISSUE THREAD

**Issue by TomasKulhanek** [creative-connections/Bodylight-Scenarios#42]
Nahrávání webového simulátoru může trvat až několik sekund (stahuje se 9-40 MB). 
Úkolem je vytvořit jednoduchou animaci - animovaný GIF, co nejmenší velikosti, který se zobrazí první na stránce a pak se čeká na nahrání zbytku.
První prototyp je animovaná laboratorní baňka:
![loading.gif](https://bodylight.physiome.cz/Bodylight-Scenarios/loading.gif)

**Comment by KlaraGrafik** [comment]
Ok, a můžu pracovat např. i s logem Bodylight, nebo radši nějaký "anonymní" předmět jako ta zkumavka apod.?

![Bodylight_logo_final1_Kreslicí plátno 1 kopie 2](https://user-images.githubusercontent.com/55106028/98343878-c3b74480-2012-11eb-882d-97ec42375719.jpg)

**Comment by KlaraGrafik** [comment]
![Bodylight_loading](https://user-images.githubusercontent.com/55106028/98525656-0da16400-2279-11eb-9def-fdd408468710.gif)
![Bodylight_loading_cerna](https://user-images.githubusercontent.com/55106028/98525663-0ed29100-2279-11eb-812d-7d2fedc8b153.gif)
![Bodylight_loading_seda](https://user-images.githubusercontent.com/55106028/98525665-0f6b2780-2279-11eb-9d6a-7fa07883e43b.gif)

**Comment by KlaraGrafik** [comment]
![Bodylight_loading2_cerna](https://user-images.githubusercontent.com/55106028/98829214-3f612900-2439-11eb-9280-117dd9775290.gif)
![Bodylight_loading2_seda](https://user-images.githubusercontent.com/55106028/98829216-40925600-2439-11eb-919d-2bb8a036e91c.gif)
![Bodylight_loading2_zluta](https://user-images.githubusercontent.com/55106028/98829219-40925600-2439-11eb-855c-16b83ed93723.gif)
