### ISSUE TITLE
Simulace modelu metabolismu železa a LPS injekce

### ISSUE THREAD

**Issue by TomasKulhanek** [creative-connections/Bodylight-Scenarios#54]
LPS v předchozí verzi composeru nastavuje natvrdo hodnotu na 1 proměnnou modelu (nikoliv parametr) pokud se klikne myší. 
Tento úkon v Bodylight-Editoru v komponentě bdl-fmu rozhodí simulaci a dostane ji do nesmyslných hodnot.

![aJSmJoKskM](https://user-images.githubusercontent.com/1429487/120017805-9a79f800-bfe6-11eb-85b6-55b165ce4ab1.gif)

Podle FMU specifikace musím udělat reset simulace, pokud nastavuju non-tunable proměnnou. 

Jako workaround možno zkusit vynechat reset pro tuto proměnnou - tj. dát do komponenty možnost neresetovat instanci FMU při změně hondoty proměnné.

**Comment by kofranek** [comment]
nerozumím - jestliže je to non-tunable proměnná, tak je asi reset nutností
? To že se to po resetu dostane do nesmyslných hodnot může být způsobeno
špatným nastavením inocializace modelu. Když ale neresetuju model (jak
chápu že se nenastaví jednotný počátek kroku všech proměnných) - tak
simulaci změním uprostřed časového kroku a můžu dostat nepřesné nebo
nesmyslné hodnoty.

pá 28. 5. 2021 v 19:00 odesílatel Tomas Kulhanek ***@***.***>
napsal:

**Comment by TomasKulhanek** [comment]
Chyba byla v definici komponenty a v parsování hodnot, FMI přijalo hodnotu NaN.
