### ISSUE TITLE
Obrázek s anatomicko histologickým kontextem duodena a buňky enterocytu

### ISSUE THREAD

**Issue by TomasKulhanek** [creative-connections/Bodylight-Scenarios#56]
V první kapitole v duodenu by měl být i anatomický kontext, kde se buňka (která je v simulátorech duodena) nachází. Ukol je tedy vytvořit obrázek obdobný jako v Encyklopedia Britannica, s českými příp. angl. popisky, Popis pod obrázkum bude: "Následující simulátory představují fyziologické funkce buňky enterocytu v duodenu při vstřebávání železa. Umístění buněk enterocytu v tenkém střevě (duodenu) a v celkové anatomii člověka."

 ![obrazek encyclopedia britanica](https://lh4.googleusercontent.com/gG1_0x7NrZda-ZVoko8Uz9TnLaAEN5O3bdbtQnGxoxDv-kvgYrPsNJkrMykCUqsZBGQ9v6qPj4GbUuuU6szwUJSAJ4_1zeGelBP_ijlFVRWPC_gQKKkzBg-aioR4M_MDduhf-yvO)

**Comment by Madrock24** [comment]
Nazdárek Tome, posílám ten obrázek

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Bez
virů. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

st 9. 6. 2021 v 9:50 odesílatel Tomas Kulhanek ***@***.***>
napsal:
