### ISSUE TITLE
Kostra, kuze, zily, tepny - 3D objekty

### ISSUE THREAD

**Issue by TomasKulhanek** [creative-connections/Bodylight-Scenarios#8]
Vytvorit 3D objekty pro virtualniho pacienta, ktere by se mohli zapinat,vypinat, zpruhlednit, rozsvitit.

- [x] kostra - p:\KofrlabData\3DModely\lymphatic_system\ nebo https://skfb.ly/6GVDu
- [x] nafitovat kuzi na kostru
- [ ] zily, tepny 
- [ ] prusvitny plan 

vysledek do p:\KofrlabData\3DModely

**Comment by VeronikaLys** [comment]
Aktuální použitý skeleton je přidaný do složky 3Dmodels/base_skeleton

**Comment by TomasKulhanek** [comment]
1. Nesedi souradnice plic a dalsich modelu, proto bych poprosil o synchronizaci. Doporucuji podle exportu ktery jsem udelal.
2. Dale jsem trochu reorganizoval strukturu v p:\KofrlabData\3DModely\
Prvni adresar je vzdycky cesky nazev systemu, ktereho modely jsou v nem. 
Druhy adresar uz jsou ruzne pracovni nebo jine adresare s daty
3. Exportoval jsem kostru z bodyparts, porovnej ji s tou kterou delas p:\KofrlabData\3DModely\kostra\exportBodyParts\
4. Exportoval jsem kuzi, ktera sedi na tu kostru p:\KofrlabData\3DModely\kuze\exportBodyParts\
5. Exportoval jsem veny a arterie ktere sedi na tu kostru p:\KofrlabData\3DModely\kardiovaskularnisystem\exportBodyParts\
6. Muzes prosim porovnat jestli s tvymi dosavadnimi modely a pripadne skalibrovat s kostrou tady, podle ni bych chtel kalibrovat dalsi organy, protoze vypada, ze ty veci dohromady velikostne nejlepe sedi odtud.

Bodyparts jsou http://lifesciencedb.jp/bp3d/# a muzu udelat export, pripadne probrat modely ve dvojici.

**Comment by TomasKulhanek** [comment]
navic jeste"
- [ ] textura na kosti
- [ ] jina barva chrupavek (mezi zebrama a hrudni kosti)

![texturakostichrupavky](https://filedn.com/lHGc7w3H4jOpIe46u1nPt57/images/texturakostichrupavky.PNG)
