### ISSUE TITLE
Konverze vybrane prezentace z atlasu fyziologie a patofyziologie do HTML5 canvasu a javascriptu.

### ISSUE THREAD

**Issue by TomasKulhanek** [creative-connections/Bodylight-Scenarios#9]
Pro ucely porovnani vice moznosti a rozhodnuti o dalsim postupu
- [x] konverze z adobe flash jako nekolik animovanych slidu, ktere se v prubehu prehravani meni/prepinaji, audio mozno samostatne pres <audio>a synchronizovat spusteni a pausu (asi nova tlacitka)

**Comment by TomasKulhanek** [comment]
Exportu chybi nejake png soubory. Prehrani pada v chrome:
<details>
<summary>images/07_pacemakerov%C3%BD%20potencial_HTML5%20Canvas_atlas_.png?1567610036051:1 GET file:///C:/Users/tomas/Google%20Drive/TrenazerProjekty/cirkulace/images/07_pacemakerov%C3%BD%20potencial_HTML5%20Canvas_atlas_.png?1567610036051 net::ERR_FILE_NOT_FOUND
</summary>

Image (async)
b.load @ createjs-2015.11.26.min.js:15
b.load @ createjs-2015.11.26.min.js:15
b.load @ createjs-2015.11.26.min.js:16
b._loadItem @ createjs-2015.11.26.min.js:15
b._loadNext @ createjs-2015.11.26.min.js:15
b.setPaused @ createjs-2015.11.26.min.js:15
b.loadManifest @ createjs-2015.11.26.min.js:15
init @ 07_pacemakerový potencial_HTML5 Canvas.html:31
onload @ 07_pacemakerový potencial_HTML5 Canvas.html:62
images/07_pacemakerov%C3%BD%20potencial_HTML5%20Canvas_atlas_2.png?1567610036055:1 GET file:///C:/Users/tomas/Google%20Drive/TrenazerProjekty/cirkulace/images/07_pacemakerov%C3%BD%20potencial_HTML5%20Canvas_atlas_2.png?1567610036055 net::ERR_FILE_NOT_FOUND
Image (async)
b.load @ createjs-2015.11.26.min.js:15
b.load @ createjs-2015.11.26.min.js:15
b.load @ createjs-2015.11.26.min.js:16
b._loadItem @ createjs-2015.11.26.min.js:15
b._loadNext @ createjs-2015.11.26.min.js:15
b._handleError @ createjs-2015.11.26.min.js:15
(anonymous) @ createjs-2015.11.26.min.js:12
b._dispatchEvent @ createjs-2015.11.26.min.js:12
b.dispatchEvent @ createjs-2015.11.26.min.js:12
b._sendError @ createjs-2015.11.26.min.js:15
b.handleEvent @ createjs-2015.11.26.min.js:15
(anonymous) @ createjs-2015.11.26.min.js:12
b._dispatchEvent @ createjs-2015.11.26.min.js:12
b.dispatchEvent @ createjs-2015.11.26.min.js:12
b._handleError @ createjs-2015.11.26.min.js:15
(anonymous) @ createjs-2015.11.26.min.js:16
error (async)
b.load @ createjs-2015.11.26.min.js:15
b.load @ createjs-2015.11.26.min.js:15
b.load @ createjs-2015.11.26.min.js:16
b._loadItem @ createjs-2015.11.26.min.js:15
b._loadNext @ createjs-2015.11.26.min.js:15
b.setPaused @ createjs-2015.11.26.min.js:15
b.loadManifest @ createjs-2015.11.26.min.js:15
init @ 07_pacemakerový potencial_HTML5 Canvas.html:31
onload @ 07_pacemakerový potencial_HTML5 Canvas.html:62
createjs-2015.11.26.min.js:12 Uncaught TypeError: Cannot read property 'getContext' of undefined
    at a.b._parseData (createjs-2015.11.26.min.js:12)
    at new a (createjs-2015.11.26.min.js:12)
    at handleComplete (07_pacemakerový potencial_HTML5 Canvas.html:44)
    at 07_pacemakerový potencial_HTML5 Canvas.html:29
    at a.b._dispatchEvent (createjs-2015.11.26.min.js:12)
    at a.b.dispatchEvent (createjs-2015.11.26.min.js:12)
    at a.b._sendComplete (createjs-2015.11.26.min.js:15)
    at a.b._loadNext (createjs-2015.11.26.min.js:15)
    at a.b._handleError (createjs-2015.11.26.min.js:15)
    at createjs-2015.11.26.min.js:12

</details>

**Comment by VeronikaLys** [comment]
Animate některé objekty exportuje ne jako vektory, ale jako textury pro zrychlení vykreslování. Jsou ve složce img, která je potřeba k exportu připojit. Bohužel jsem si to neuvědomila, připojím ji.

**Comment by TomasKulhanek** [comment]
p:\KofrlabData\UpgradeAtlasu\02 Elektrické vlastnosti myokardální buňky\
